package org.opendatamesh.platform.pp.notification.rest.v2.resources.notification.usecases.replay;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.notification.rest.v2.resources.event.EventRes;
import org.opendatamesh.platform.pp.notification.rest.v2.resources.notification.NotificationStatusRes;
import org.opendatamesh.platform.pp.notification.rest.v2.resources.subscription.SubscriptionRes;
import org.opendatamesh.platform.pp.notification.utils.resources.VersionedRes;

@Schema(name = "NotificationReplayResponseRes", description = "Response resource returned after replaying a notification. " +
        "Contains the replayed notification with its updated status and details.")
public class NotificationReplayResponseRes {

    @Schema(
            description = "The replayed notification. After replay, the notification status is set to PROCESSING " +
                    "and it is dispatched again to the observer. The status may change to PROCESSED or " +
                    "FAILED_TO_DELIVER based on the dispatch result.",
            required = true
    )
    private Notification notification;

    public NotificationReplayResponseRes() {
    }

    public Notification getNotification() {
        return notification;
    }

    public void setNotification(Notification notification) {
        this.notification = notification;
    }

    @Schema(name = "Notification", description = "Replayed notification details")
    public static class Notification extends VersionedRes {

        @Schema(
                description = "Unique identifier of the notification (autogenerated sequence ID)",
                example = "101",
                required = true
        )
        private Long sequenceId;

        @Schema(
                description = "Current status of the notification. After replay, this is typically PROCESSING. " +
                        "It may change to PROCESSED if the observer successfully processes it, or " +
                        "FAILED_TO_DELIVER if the dispatch fails again.",
                example = "PROCESSING",
                required = true
        )
        private NotificationStatusRes status;

        @Schema(
                description = "Event associated with this notification. Contains details about the event " +
                        "that triggered the notification.",
                required = true
        )
        private EventRes event;

        @Schema(
                description = "Subscription that triggered this notification. Contains observer details " +
                        "including the server base URL and API version used for dispatch.",
                required = true
        )
        private SubscriptionRes subscription;

        @Schema(
                description = "Error message if notification delivery failed. This field is cleared when " +
                        "the notification is replayed and will be populated again only if the dispatch fails.",
                example = "Connection timeout while reaching observer server"
        )
        private String errorMessage;

        public Notification() {
        }

        public Long getSequenceId() {
            return sequenceId;
        }

        public void setSequenceId(Long sequenceId) {
            this.sequenceId = sequenceId;
        }

        public NotificationStatusRes getStatus() {
            return status;
        }

        public void setStatus(NotificationStatusRes status) {
            this.status = status;
        }

        public EventRes getEvent() {
            return event;
        }

        public void setEvent(EventRes event) {
            this.event = event;
        }

        public SubscriptionRes getSubscription() {
            return subscription;
        }

        public void setSubscription(SubscriptionRes subscription) {
            this.subscription = subscription;
        }

        public String getErrorMessage() {
            return errorMessage;
        }

        public void setErrorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
        }

    }
}
