package org.opendatamesh.platform.pp.notification.rest.v2.resources.event;

public enum EventType {
    DATAPRODUCT_CREATED,
    DATAPRODUCT_UPDATED,
    DATAPRODUCT_DELETED,
    DATAPRODUCT_VERSION_CREATED,
    DATAPRODUCT_VERSION_UPDATED,
    DATAPRODUCT_VERSION_DELETED,
    BLUEPRINT_CREATED,
    BLUEPRINT_UPDATED,
    BLUEPRINT_DELETED,
    POLICY_CREATED,
    POLICY_UPDATED,
    POLICY_DELETED
}
