package org.opendatamesh.platform.pp.notification.rest.v2.resources.event;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.notification.utils.resources.VersionedRes;

public class EventRes extends VersionedRes {

    @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
    private Long sequenceId;

    @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
    private String resourceType;

    @Schema(description = "UUID of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
    private String resourceIdentifier;

    @Schema(description = "Type of event emitted", example = "CREATED")
    private EventType type;

    @Schema(description = "Version of the event type definition", example = "1.0.0")
    private String eventTypeVersion;

    @Schema(description = "Serialized JSON content of the event", example = "{\"resource\":\"dataProduct\",\"action\":\"CREATED\"}")
    private String eventContent;

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    public void setResourceIdentifier(String resourceIdentifier) {
        this.resourceIdentifier = resourceIdentifier;
    }

    public EventType getType() {
        return type;
    }

    public void setType(EventType type) {
        this.type = type;
    }

    public String getEventTypeVersion() {
        return eventTypeVersion;
    }

    public void setEventTypeVersion(String eventTypeVersion) {
        this.eventTypeVersion = eventTypeVersion;
    }

    public String getEventContent() {
        return eventContent;
    }

    public void setEventContent(String eventContent) {
        this.eventContent = eventContent;
    }
}
