package org.opendatamesh.platform.pp.notification.rest.v2.resources.notification;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.notification.rest.v2.resources.event.EventRes;
import org.opendatamesh.platform.pp.notification.rest.v2.resources.subscription.SubscriptionRes;
import org.opendatamesh.platform.pp.notification.utils.resources.VersionedRes;

@Schema(name = "NotificationRes", description = "Resource representation of a notification entity")
public class NotificationRes extends VersionedRes {

    @Schema(description = "Unique identifier of the notification (autogenerated sequence ID)", example = "101")
    private Long sequenceId;

    @Schema(description = "Current status of the notification", example = "DELIVERED")
    private NotificationStatusRes status;

    @Schema(description = "Event associated with this notification")
    private EventRes event;

    @Schema(description = "Subscription that triggered this notification")
    private SubscriptionRes subscription;

    @Schema(description = "Error message if notification delivery failed", example = "Connection timeout while reaching observer server")
    private String errorMessage;

    public NotificationRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public NotificationStatusRes getStatus() {
        return status;
    }

    public void setStatus(NotificationStatusRes status) {
        this.status = status;
    }

    public EventRes getEvent() {
        return event;
    }

    public void setEvent(EventRes event) {
        this.event = event;
    }

    public SubscriptionRes getSubscription() {
        return subscription;
    }

    public void setSubscription(SubscriptionRes subscription) {
        this.subscription = subscription;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

}